[package]
name = "quantum_vault"
edition = "2024"    # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "main", use-environment = "testnet_utopia" }
#world = { r.mvr = "@evefrontier/world-uat", use-environment = "testnet_utopia" }

[dep-replacements.testnet]
world = { use-environment ="testnet_utopia" }

[environments]
testnet_internal = "4c78adac"
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"